name: Cloud Admin

on: #[push]

jobs:
  builds:

    runs-on: ubuntu-latest

    env:
      L0_COMPANY_NAME: MyCleanTechComp
      CLOUD_USER_GITHUB: yabinboxes
      CLOUD_EMAIL_GITHUB: yabin.monroy.1@gmail.com
      DEFAULT_CLOUD_PROVIDER: GCP
      CLOUD_REPO_LOCATION: yabinboxes/cloud-admin-ui
      CLOUD_RUN: yabinboxes/gcp-deploy-cloud-run
      APP_PORT: 5000

#    container:
#      image: node:14-alpine
#      options: --network-alias testHost

#    services:
#      selenium-hub:
#        image: selenium/hub:3.141.59
#        ports:
#          - 4444:4444


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
#      - run: |
#          npm ci
#          npm run dev > /dev/null 2>&1 &
#          sleep 20s

 #     - name: Container is healthy
 #       run: |
 #         curl -X GET http://localhost:5000

      - name: Exec Autodeploy
        run: |
          curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" \
          -d "{\"cloudRun\": \"${{env.CLOUD_RUN}}\", \"cloudRepoLocation\": \"${{env.CLOUD_REPO_LOCATION}}\", \
          \"cloudUserGithub\": \"${{env.CLOUD_USER_GITHUB}}\", \"cloudEmailGithub\": \"${{env.CLOUD_EMAIL_GITHUB}}\", \
          \"appPort\": \"${{env.APP_PORT}}\",
          \"companyName\": \"${{env.L0_COMPANY_NAME}}\", \"apiTokenGithub\": \"${{ secrets.API_TOKEN_GITHUB }}\" }" \
          http://localhost:5000/autodeploy